"use client";
//서버 컴포넌트에서 API(useState)를 사용하면 에러가 뜸, 클라이언트 컴포넌트로 변경
import Link from 'next/link'
import './globals.css'
import { useEffect, useState } from 'react'


// export const metadata = {
//   title: 'Web tutorial',
//   description: 'Generated by ',
// }


//next.js docs /Route Handlers 
//https://nextjs.org/docs/app/building-your-application/routing/route-handlers
//const [topics, setTopics] = useState([]); 가져온 데이터를 사용하기위해 state가 필요하다
//useEffect(()=>fetch().then().then()); 서버 컴포넌트
//에러 발생 It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
//"use clinent";
//에러 발생 export const metadata 서버 컴포넌트에만 사용가능

export default function RootLayout({ children }) {
  const [topics, setTopics] = useState([]);
  useEffect(() => {
    fetch('https://localhost:9999/topics')
    .then(resp=>resp.json())
    .then(result=>{
      setTopics(result);
    });
  }, []);
  return (
    <html>
      <body>
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          <li><Link href='/read/1'>html</Link></li>
          <li><Link href='/read/2'>css</Link></li>
        </ol>
          { children }
          <ul>
            <li><Link href='/create'>Create</Link></li>
            <li><Link href='/update/1'>Update</Link></li>
            <li><input type='button' value="delete"/></li>
          </ul>
      </body>
    </html>
  )
}

//single page application_ Hardcoding 

// export default function RootLayout({ children }) {
//   return (
//     <html>
//       <body>
//         <h1><Link href='/'>WEB</Link></h1>
//         <ol>
//           <li><Link href='/read/1'>html</Link></li>
//           <li><Link href='/read/2'>css</Link></li>
//         </ol>
//           { children }
//           <ul>
//             <li><Link href='/create'>Create</Link></li>
//             <li><Link href='/update/1'>Update</Link></li>
//             <li><input type='button' value="delete"/></li>
//           </ul>
//       </body>
//     </html>
//   )
// }

