server:
  port: 8000

spring:
  application:
    name: SSGPOINT_APP

  jpa:
    hibernate:          # update : 변경된 부분만 업데이트
      ddl-auto: create  # create : 실행 시점에 테이블을 다 지우고, 다시 테이블 자동 생성
      format_sql: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/DB명
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver